# Generated by Django 3.0.6 on 2020-05-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Different_Ind_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('different_ind_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Different_Ind_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_designation', models.CharField(max_length=200)),
                ('person_email', models.CharField(max_length=200)),
                ('person_phone', models.IntegerField()),
                ('account_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employer.Account_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('business_description', models.TextField()),
                ('trade_licence_no', models.IntegerField()),
                ('account_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employer.Account_Info')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Different_Ind_Type')),
                ('industry_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employer.Industry_Type')),
            ],
        ),
    ]
