# Generated by Django 3.0.6 on 2020-05-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_auto_20200515_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Division'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='trade_licence_no',
            field=models.IntegerField(max_length=25),
        ),
    ]
