# Generated by Django 3.0.4 on 2020-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_companyinfo_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='person_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
