# Generated by Django 3.0.4 on 2020-06-05 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_auto_20200529_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='trade_licence_no',
            new_name='licence_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='person_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='person_email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='person_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='division',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='different_ind_type',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(default=datetime.datetime(2020, 6, 5, 11, 47, 57, 396379, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b_address',
            field=models.TextField(default=datetime.datetime(2020, 6, 5, 11, 49, 51, 223707, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='websiteurl',
            field=models.URLField(default=datetime.datetime(2020, 6, 5, 11, 53, 15, 988136, tzinfo=utc), max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 6, 5, 11, 57, 41, 386854, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(default=datetime.datetime(2020, 6, 5, 11, 58, 9, 212620, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='Employer.Division'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='IndustryType',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='DifferentIndType',
            new_name='IndustryTypeMaster',
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.District')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryTypeSlave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry_type_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.IndustryTypeMaster')),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='industry_type_slave',
            field=models.ManyToManyField(to='Employer.IndustryTypeSlave'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='thana',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Employer.Thana'),
            preserve_default=False,
        ),
    ]
